package SQL_Server;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jelfr
 */
public class Edit extends javax.swing.JFrame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
   jTable1.getColumnModel().getColumn(3).setMinWidth(0);
    jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
    jTextField5.setVisible(false);
    
    }

    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://;databaseName=TBD_TRAB1";
    String username = "galactic21";
    String password = "wanrltw1";
    String Atr1 = null;
    String Atr2 = null;
    String Atr3 = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Executar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Designacao");

        jLabel3.setText("Preco");

        jLabel4.setText("Número da Factura");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton2.setText("Procurar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField5.setText("jTextField5");

        jLabel5.setText("Tempo de Pesquisa");

        jLabel6.setText("s");

        jLabel7.setText("Tempo de Execução");

        jLabel8.setText("s");

        jLabel9.setText("Nivel de Isolamento");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Update Normal", "Read Uncommitted", "Read Committed", "Repeatable Read ", "Serializable" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField1))))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        select_table("select Nome,Designacao,Preco,ProdutoID from  Factura,FactLinha where Factura.FacturaID = FactLinha.FacturaID and Factura.FacturaID = ?;");
  
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void select_table(String sql){
         ResultSet rs = null;
        long tinicial =System.currentTimeMillis();
          
        try{
           
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jTextField3.getText());
            rs = pst.executeQuery();
          
            if (rs.next() ) {
                 rs = pst.executeQuery();
                while(rs.next())
                {
                    rs = pst.executeQuery();
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                  
                    jTable1.getColumnModel().getColumn(3).setMinWidth(0);
                    jTable1.getColumnModel().getColumn(3).setMaxWidth(0);
                } 
            } else {
                    JOptionPane.showMessageDialog(this, "Não existe a fatura. Tente Novamente!");
    
            }
              long tfinal = System.currentTimeMillis()-tinicial;
    
     
      // jTextField6.setText(String.valueOf(total)); 
       jTextField6.setText(String.valueOf((tfinal)/1000.0));

        System.out.println("Tempo de Pesquisa = " + (tfinal)/1000.0+" segundos\n");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
           
        }
    }
    
    private void update_normal(String sql,String sql1, String sql2, String query){
          long tinicial =System.currentTimeMillis();
 
        try{
           
             // text1 = jTextField1.getText();
              System.out.println("\nNome 2:"+Atr1);
                 System.out.println("\nDesignacao 2: "+Atr2);
                System.out.println("\nPreco 2:"+Atr3);
                 if(Atr1.matches(jTextField1.getText())){
                  System.out.println("O campo nome nao foi alterado\n");
              //   JOptionPane.showMessageDialog(this, "O campo Nome não foi alterado");
              }else{
                 
                     Statement1(sql, query);
                    
                    //JOptionPane.showMessageDialog(this, "Update com sucesso");
                          
                    
                  }
              
                   if(Atr2.matches(jTextField2.getText())){
               System.out.println("O campo Designacao nao foi alterado\n");
            //   JOptionPane.showMessageDialog(this, "O campo Designacao não foi alterado!");
           }else{
             Statement2(sql1, query);
           
           }
           
           if(Atr3.matches(jTextField4.getText())){
                  System.out.println("O campo Preco nao foi alterado\n");
                 // JOptionPane.showMessageDialog(this, "O campo Preco não foi alterado!");
           }else{
     
              Statement3(sql2, query);
             }
         
            
            
        
                   long tfinal = System.currentTimeMillis()-tinicial;
    
     
      // jTextField6.setText(String.valueOf(total)); 
       jTextField7.setText(String.valueOf((tfinal)/1000.0));

        System.out.println("Tempo de Update = " + (tfinal)/1000.0+" segundos\n");
       
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void Statement1(String sql ,String query){
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
          
          
                     PreparedStatement pst = con.prepareStatement(sql);
                     pst.setString(1, jTextField1.getText());
                     Atr1 = jTextField1.getText();
                    // System.out.println(" Texto 3:"+text1);
                     pst.setString(2, jTextField3.getText());
                     pst.setString(3, jTextField1.getText());
                     pst.executeUpdate();
                     
                     select_table(query);
       
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
       private void Statement2(String sql ,String query){
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
          
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jTextField2.getText());
              Atr2 = jTextField2.getText();
             pst.setString(2, jTextField3.getText());
             pst.setString(3, jTextField5.getText());
             pst.setString(4, jTextField2.getText());
             pst.executeUpdate();
             select_table(query);
       //JOptionPane.showMessageDialog(this, "Update com sucesso");
       
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
          
       private void Statement3(String sql ,String query){
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
          
             PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1, jTextField4.getText());
             pst.setString(2, jTextField3.getText());
             pst.setString(3, jTextField5.getText());
             pst.setString(4, jTextField4.getText());
             pst.executeUpdate();
                          select_table(query);
            // JOptionPane.showMessageDialog(this, "Update com sucesso");
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

       private void read_uncommitted(String sql,String sql1, String sql2, String query){
          long tinicial =System.currentTimeMillis();

        try{
           
             // text1 = jTextField1.getText();
              System.out.println("\nNome 2:"+Atr1);
                 System.out.println("\nDesignacao 2: "+Atr2);
                System.out.println("\nPreco 2:"+Atr3);
                 if(Atr1.matches(jTextField1.getText())){
                  System.out.println("O campo nome nao foi alterado\n");
              //   JOptionPane.showMessageDialog(this, "O campo Nome não foi alterado");
              }else{
                
                     
                     //select_table(query);
                      
                     Statement4(sql, query);
                     System.out.println("O campo nome nao foi alterado\n");
                    //JOptionPane.showMessageDialog(this, "Update com sucesso");
                          
                    
                  }
              
                   if(Atr2.matches(jTextField2.getText())){
               System.out.println("O campo Designacao nao foi alterado\n");
            //   JOptionPane.showMessageDialog(this, "O campo Designacao não foi alterado!");
           }else{
                         
             Statement5(sql1, query);

           }
           
           if(Atr3.matches(jTextField4.getText())){
                  System.out.println("O campo Preco nao foi alterado\n");
                 // JOptionPane.showMessageDialog(this, "O campo Preco não foi alterado!");
           }else{
         
              Statement6(sql2, query);
         
             }
         
            
            
        
                   long tfinal = System.currentTimeMillis()-tinicial;
    
     
      // jTextField6.setText(String.valueOf(total)); 
       jTextField7.setText(String.valueOf((tfinal)/1000.0));

        System.out.println("Tempo de Update = " + (tfinal)/1000.0+" segundos\n");
       
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void Statement4(String sql ,String query){
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
          
          
                     PreparedStatement pst = con.prepareStatement(sql);
                     pst.setString(1, jTextField1.getText());
                     Atr1 = jTextField1.getText();
                    // System.out.println(" Texto 3:"+text1);
                     pst.setString(2, jTextField3.getText());
                      
                     pst.executeUpdate();
                      select_table(query);
                 
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
       private void Statement5(String sql ,String query){
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
          
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jTextField2.getText());
              Atr2 = jTextField2.getText();
             pst.setString(2, jTextField3.getText());
             pst.setString(3, jTextField5.getText());
               select_table(query);
               pst.executeUpdate();
                     
       //JOptionPane.showMessageDialog(this, "Update com sucesso");
       
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
          
       private void Statement6(String sql ,String query){
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
          
             PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1, jTextField4.getText());
             pst.setString(2, jTextField3.getText());
             pst.setString(3, jTextField5.getText());
               select_table(query);
             pst.executeUpdate();
                  
            // JOptionPane.showMessageDialog(this, "Update com sucesso");
             }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       TableModel model = (TableModel)jTable1.getModel();
       int selectedRow = jTable1.getSelectedRow();
       jTextField1.setText(model.getValueAt(selectedRow, 0).toString());
       jTextField2.setText(model.getValueAt(selectedRow, 1).toString());
       jTextField4.setText(model.getValueAt(selectedRow, 2).toString());
       jTextField5.setText(model.getValueAt(selectedRow, 3).toString());
       
       Atr1 = jTextField1.getText();
       System.out.println("Nome 1: "+Atr1);
        Atr2 = jTextField2.getText();
       System.out.println("Designacao 1: "+Atr2);
        Atr3 = jTextField4.getText();
       System.out.println(" Preco 1: "+Atr3);
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
           //Variaveis do Update Normal
           String sqlN ="Begin Transaction update Factura set Nome = ? where Factura.FacturaID = ? insert Into LogOperations(EventType,Objecto,Valor) Values('U','Nome',?) commit;";
           String sql1N ="Begin Transaction update FactLinha set Designacao = ? where FactLinha.FacturaID = ? and ProdutoID =  ?  insert Into LogOperations(EventType,Objecto,Valor) Values('U','Designacao',?); commit;";
           String sql2N ="Begin Transaction update FactLinha set Preco = ? where FactLinha.FacturaID = ? and ProdutoID =  ? insert Into LogOperations(EventType,Objecto,Valor) Values('U','Preco',?); commit;";
           String queryN ="select Nome,Designacao,Preco,ProdutoID from  Factura,FactLinha where Factura.FacturaID = FactLinha.FacturaID and Factura.FacturaID = ?;";
           
           //Variaveis do Read Uncommited
           String sqlRU ="Begin Transaction update Factura set Nome = ? where Factura.FacturaID = ? WAITFOR DELAY '00:00:10' ROLLBACK;";
           String sql1RU ="Begin Transaction update FactLinha set Designacao = ? where FactLinha.FacturaID = ? and ProdutoID =  ?  WAITFOR DELAY '00:00:10' ROLLBACK;";
           String sql2RU ="Begin Transaction update FactLinha set Preco = ? where FactLinha.FacturaID = ? and ProdutoID =  ? WAITFOR DELAY '00:00:10' ROLLBACK;";
           String queryRU ="SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED select Nome,Designacao,Preco,ProdutoID from Factura,FactLinha with (NOLOCK) where Factura.FacturaID = FactLinha.FacturaID and Factura.FacturaID = ?;";
         
               switch(jComboBox1.getSelectedIndex()){
                      case 0: 
                          System.out.println("Selecione:");
                          JOptionPane.showMessageDialog(this, "Selecione o Nivel de Isolamento");
                          break;
                      case 1:
                           update_normal(sqlN, sql1N,sql2N , queryN);
                           break;
                      case 2:
                         
                           read_uncommitted(sqlRU, sql1RU,sql2RU ,queryRU);
                           select_table(queryRU);
                           
                           break;
             
                     
              }
           
            
      
             
           
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
     
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
           
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables


}