/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BDTransactionsManagement;


import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Random;


/**
 *
 * @author Yoann Resende
 */
public class WorkUI extends javax.swing.JFrame {

    /**
     * Creates new form WorkUI
     */
    public WorkUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de operações");

        jLabel2.setText("Nível de isolamento");

        jLabel3.setText("Inserir");

        jLabel4.setText("Delete");

        jLabel5.setText("Update");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READ COMMITED", "READ UNCOMMITED", "REPEATABLE READ", "SERIALIZABLE" }));

        jLabel6.setText("20%");

        jLabel7.setText("30%");

        jLabel8.setText("50%");

        jLabel9.setText("Work");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(74, 74, 74)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n = Integer.parseInt(jTextField2.getText());
        Random aleat = new Random();
        int nbalea;
        isolationlevel = jComboBox1.getSelectedItem().toString().toUpperCase();
        for(int i = 1 ; i <= n ; i++) {
            nbalea = aleat.nextInt(100);
            if(nbalea < 20) {
                    insert();
            }else if(20 <= nbalea && nbalea < 50){
                    delete();
            }else {
                    update();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorkUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    private DateFormat dateFormat = new SimpleDateFormat("yyMMddHHmmssZ");
    private Date date = new Date() ; 
    private String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private String url = "jdbc:sqlserver://DESKTOP-SINCFA7\\MSSQLSERVER2;databaseName=TBD_TRAB1";
    private String username = "aluno";
    private String password = "aluno";
    private String isolationlevel = "SERIALIZABLE";
    private ResultSet rs = null;                                  

   private void update() {
        query("select MAX(FacturaID) from  Factura;");
        int maxfact = 0;
        try {
            maxfact = rs.getInt(1);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        rs = null;
        Random rd = new Random();
        int rand = rd.nextInt(maxfact);
        date = new Date() ;
        query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('U','BEGIN', 'Fatura'," + rand + "," + dateFormat.format(date) + ");");
        query("BEGIN TRANSACTION");
        query("SET TRANSACTION ISOLATION LEVEL " + isolationlevel);
        query_update("UPDATE Factura SET nome = 'ABC' where FacturaID = " + rand + ";",rand);
        query("COMMIT;");
        query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('U','COMMIT', 'Fatura'," + rand + "," + dateFormat.format(date) + ");");
   }

	private void delete() {
            query("select MAX(FacturaID) from Factura;");
            int maxfact = 0;
            try {
                maxfact = rs.getInt(1);
            } catch (SQLException e) {
                e.printStackTrace();
            }
            Random rd = new Random();
            int rand = rd.nextInt(maxfact);
            date = new Date() ;
            query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('D','BEGIN', 'Fatura e FactLinha'," + rand + "," + dateFormat.format(date) + ");");
            query("BEGIN TRANSACTION");
            query("SET TRANSACTION ISOLATION LEVEL " + isolationlevel);
            query_delete("Delete from Factura where Factura.FacturaID = " + rand + ";",rand);
            query_delete("Delete from FactLinha where FactLinha.FacturaID = " + rand + ";",rand);
            query("COMMIT;");
            query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('D','COMMIT', 'Fatura e FactLinha'," + rand + "," + dateFormat.format(date) + ");");
	}

	private void insert() {
            query("select MAX(FacturaID) from Factura;");
            int maxfact = 0;
            try {
                maxfact = rs.getInt(1);
            } catch (SQLException e) {
                e.printStackTrace();
            }
            int newfactid = maxfact +1;
            int cliente = 5;
            int produto1 = 10;
            int produto2 = 11;
            date = new Date() ;
            query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('I','BEGIN', 'Fatura e FactLinha'," + newfactid + "," + dateFormat.format(date) + ");");
            query("BEGIN TRANSACTION");
            query("SET TRANSACTION ISOLATION LEVEL " + isolationlevel);
            query_insert("INSERT INTO Factura(FaturaID,ClienteID,Nome) VALUES (" + newfactid  +"," + cliente + ",'Insert Nome');",newfactid);
            query_insert("INSERT INTO FactLinha(FaturaID,ProdutoID,Designacao) VALUES (" + newfactid  +"," + produto1+",'Insert Produto');",newfactid);
            query_insert("INSERT INTO FactLinha(FaturaID,ProdutoID,Designacao) VALUES (" + newfactid  +"," + produto2+",'Insert Produto');",newfactid);
            query("COMMIT;");
            query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('I','COMMIT', 'Fatura e FactLinha'," + newfactid + "," + dateFormat.format(date) + ");");	
	}

   
   private void query(String sql){
      rs = null;
      try{
          Class.forName(driver);
          Connection con = DriverManager.getConnection(url, username, password);
          PreparedStatement pst = con.prepareStatement(sql);
          rs = pst.executeQuery();
          /*Statement stmt = null;
          stmt = con.createStatement();
          String selectQ = sql;
          rs = stmt.executeQuery(selectQ);*/
      }catch (Exception e){
      }
  }
  
  private void query_update(String sql, int update){
        rs = null;
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch (Exception e){
           query("ROLLBACK;");
           query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('U','ROLLBACK', 'Fatura'," + update + "," + dateFormat.format(date) + ");");
        }
 }
  
  private void query_delete(String sql, int update){
        rs = null;
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch (Exception e){
           date = new Date() ;
           query("ROLLBACK;");
           query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('D','ROLLBACK', 'Fatura e FactLinha'," + update + "," + dateFormat.format(date) + ");");
        }
    }
  private void query_insert(String sql, int update){
        rs = null;
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, username, password);
            PreparedStatement pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
        }catch (Exception e){
           date = new Date() ;
           query("ROLLBACK;");
           query("Insert into LogOperations(EventType,Objeto,Valor,Referencia) Values ('I','ROLLBACK', 'Fatura e FactLinha'," + update + "," + dateFormat.format(date) + ");");
        }
    }

}
